### ISSUE TITLE
pushover crash

### ISSUE THREAD

**Issue by Ascendin81** [jef/nvidia-snatcher#149]
### Description

There was an IN STOCK false positive, but that is ok. expected... the crash is related to pushover.

I put the "user key" in for both "token" and "user".  What is "TOKEN" is it the name of the app that I chose on pushover website?  I see a "key", and I pasted it into the user field, but I don't see a token.

[6:28:10 PM] info :: ��� [bandh] msi gaming x trio IN STOCK ���
[6:28:10 PM] info :: https://www.bhphotovideo.com/c/product/1593996-REG/msi_g3080gxt10_geforce_rtx_3080_gaming.html
[6:28:11 PM] info :: ↗ playing sound
[6:28:11 PM] error :: error playing sound: Error: Couldn't find a suitable audio player
C:\nvidia-snatcher\node_modules\pushover-notifications\lib\pushover.js:146
      throw new Error(d.errors[0], res)
      ^

Error: application token is invalid
    at Pushover.errors (C:\nvidia-snatcher\node_modules\pushover-notifications\lib\pushover.js:146:13)
    at IncomingMessage.<anonymous> (C:\nvidia-snatcher\node_modules\pushover-notifications\lib\pushover.js:250:12)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1252:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nvidia-snatcher@1.4.0 start: `npm run build && node build/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nvidia-snatcher@1.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Windows 10 Pro 64bit

### Possible solution

No idea.

**Comment by Ascendin81** [comment]
ok I did 

npm install play-sound

lets see if this fixes the sound player issue.

**Comment by calebrogers** [comment]
I still got the error after installing play-sound, the mp3 was missing. Error here:

[7:48:18 PM] error :: error opening sound file: ENOENT: no such file or directory, access 'C:\git\nvidia-snatcher\notification.mp3'
C:\git\nvidia-snatcher\node_modules\pushover-notifications\lib\pushover.js:146
      throw new Error(d.errors[0], res)
      ^

Error: application token is invalid
    at Pushover.errors (C:\git\nvidia-snatcher\node_modules\pushover-notifications\lib\pushover.js:146:13)
    at IncomingMessage.<anonymous> (C:\git\nvidia-snatcher\node_modules\pushover-notifications\lib\pushover.js:250:12)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by Ascendin81** [comment]
Remove the directory, and keep the .mp3 where it is.  That will fix the "no such file or directory" error...  

but then, pushover error, what is that?

**Comment by calebrogers** [comment]
If it happens on the next false positive I'll capture more info. I dropped my own alarm mp3 in there for the current run.

**Comment by calebrogers** [comment]
[4:22:35 PM] error :: Error sending webhook: 404 status code. Response: {"message": "Unknown Webhook", "code": 10015}
E:\git\nvidia-snatcher\node_modules\pushover-notifications\lib\pushover.js:146
      throw new Error(d.errors[0], res)
      ^

Error: application token is invalid
    at Pushover.errors (E:\git\nvidia-snatcher\node_modules\pushover-notifications\lib\pushover.js:146:13)
    at IncomingMessage.<anonymous> (E:\git\nvidia-snatcher\node_modules\pushover-notifications\lib\pushover.js:250:12)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nvidia-snatcher@1.4.0 start: `npm run build && node build/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nvidia-snatcher@1.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\`````\2020-09-21T23_22_35_508Z-debug.log
