### ISSUE TITLE
I get lots of errors when i run the notification test but I still get a desktop notification however no email, should I just ignore it?

### ISSUE THREAD

**Issue by SomeRandomName105** [jef/nvidia-snatcher#231]
### Description

 When I run "npm run test:notification" I get loads of errors but I still get a desktop notification but no email sent to me.
 Here is what cmd says:
[6:17:52 AM] error :: error opening sound file: ENOENT: no such file or directory, access 'C:\nvidia-snatcher\notification.mp3'
[6:17:52 AM] error :: Error sending webhook: 404 status code. Response: {"message": "Unknown Webhook", "code": 10015}
[6:17:52 AM] error :: An API error occurred: invalid_auth
[6:17:52 AM] error :: Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials r9sm12509630eji.111 - gsmtp
[6:17:52 AM] error :: Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials c5sm12539150edt.24 - gsmtp
C:\nvidia-snatcher\node_modules\pushover-notifications\lib\pushover.js:146
      throw new Error(d.errors[0], res)
      ^

Error: application token is invalid
    at Pushover.errors (C:\nvidia-snatcher\node_modules\pushover-notifications\lib\pushover.js:146:13)
    at IncomingMessage.<anonymous> (C:\nvidia-snatcher\node_modules\pushover-notifications\lib\pushover.js:250:12)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1252:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nvidia-snatcher@1.4.0 test:notification: `npm run build && node build/__test__/notification-test.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nvidia-snatcher@1.4.0 test:notification script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lol\AppData\Roaming\npm-cache\_logs\2020-09-23T03_17_53_207Z-debug.log

I have put my email and password in the .emv file and also disabled the auto sign in block thing for gmail.
 OS is windows 10.

### Possible solution

 I don't know.

**Comment by jef** [comment]
https://github.com/jef/nvidia-snatcher/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed+env
