### ISSUE TITLE
Unable to start due to puppeteer --no-sandbox error

### ISSUE THREAD

**Issue by JadedJak** [jef/nvidia-snatcher#353]
Started giving error after latest snatcher update
Command used to start: sudo npm run start
OS: Linux Mint 19.1 x64
Error text:
(node:7863) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
[0927/204909.711513:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/mint2/nvidia-snatcher/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/home/mint2/nvidia-snatcher/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (events.js:326:22)
    at Interface.close (readline.js:424:8)
    at Socket.onend (readline.js:202:10)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1252:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7863) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7863) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Code in ./build/index.js maybe isnt working?
                   if (config_1.Config.browser.isTrusted) {
                        args.push('--no-sandbox');
                        args.push('--disable-setuid-sandbox');
                    }

**Comment by JadedJak** [comment]
Setting ownership for all folders and files to user then running without sudo appears to correct this issue.

**Comment by andrewmackrodt** [comment]
Am closing as the error is described in the output from puppeteer: `Running as root without --no-sandbox is not supported`. If you do have to run as root (I strongly advise against this), you can set the environment variable `BROWSER_TRUSTED=true`.
