### ISSUE TITLE
 UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'writeFile' of undefined

### ISSUE THREAD

**Issue by safarovd** [jef/nvidia-snatcher#459]
Here is the entire error: 

![image](https://user-images.githubusercontent.com/32182031/95144223-f8db2900-072c-11eb-8362-5f6a7019b91c.png)

`(node:508) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'writeFile' of undefined
    at PuppeteerExtraPluginAdblocker.persistToCache (C:\gpu_bot\nvidia-snatcher\node_modules\puppeteer-extra-plugin-adblocker\dist\index.cjs.js:53:27)
    at PuppeteerExtraPluginAdblocker.getBlocker (C:\gpu_bot\nvidia-snatcher\node_modules\puppeteer-extra-plugin-adblocker\dist\index.cjs.js:94:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:508) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:508) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Please, let me know if you need any further info from me. I'm pumped to get the 3080, but boy it's tough out here!

**Comment by famguy07** [comment]
I am having the exact same issue. Seeing as you closed this, what did you do to resolve it? I got the configuration file setup and confirmed with test:notification, but when running npm run start I get the following:


[15:53:15] info :: ℹ selected stores: nvidia
[15:53:15] info :: ℹ selected series: 3080
(node:17276) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'writeFile' of undefined
    at PuppeteerExtraPluginAdblocker.persistToCache (C:\Users\Zach\Documents\Nvidia Snatcher\nvidia-snatcher\node_modules\puppeteer-extra-plugin-adblocker\dist\index.cjs.js:53:27)
    at PuppeteerExtraPluginAdblocker.getBlocker (C:\Users\Zach\Documents\Nvidia Snatcher\nvidia-snatcher\node_modules\puppeteer-extra-plugin-adblocker\dist\index.cjs.js:94:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:17276) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:17276) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by famguy07** [comment]
To anyone else having the same issue, I was able to resolve it by updating Node to the latest version, deleting the node_modules folder, and rerunning the install. I am happily running the script now.
