### ISSUE TITLE
NVIDIA Snatcher fails to start with UnhandledPromiseRejectionWarning: TimeoutError

### ISSUE THREAD

**Issue by cyberpower678** [jef/nvidia-snatcher#476]
### Description

When starting NVIDIA snatcher, it fails with a timeout error.

(node:37728) UnhandledPromiseRejectionWarning: TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r800071 is guaranteed to work.
    at Timeout.onTimeout (C:\Users\<user>\nvidia-snatcher\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:204:20)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:37728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:37728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I am using the latest version of Chrome.

**Comment by cyberpower678** [comment]
Increasing the launcher timeout fixed it for me.
