### ISSUE TITLE
Issue with notification test

### ISSUE THREAD

**Issue by afcoulthard** [jef/nvidia-snatcher#477]
Script is running fine, but I am unable to run **_npm run test:notification_** successfuly 

TypeError: Cannot read property 'logLevel' of undefined
    at Object.<anonymous> (C:\Users\afcou\Desktop\nvidia-snatcher\build\logger.js:22:28)
    at Module._compile (internal/modules/cjs/loader.js:1085:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:791:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\afcou\Desktop\nvidia-snatcher\build\config.js:10:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nvidia-snatcher@1.5.0 test:notification: `npm run build && node build/__test__/notification-test.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nvidia-snatcher@1.5.0 test:notification script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\afcou\AppData\Roaming\npm-cache\_logs\2020-10-08T20_43_37_790Z-debug.log

Any ideas?

**Comment by w00druff** [comment]
https://github.com/jef/nvidia-snatcher/issues/468#issuecomment-704919683

**Comment by afcoulthard** [comment]
This fixed it, thanks.
