### ISSUE TITLE
Cannot Launch now

### ISSUE THREAD

**Issue by slikone27** [jef/nvidia-snatcher#638]
Just updated and then tried fresh install too... Wont launch now at all

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '@hijef/pushbullet'
Require stack:
- C:\Users\brian\Desktop\nvidia-snatcher\build\notification\pushbullet.js
- C:\Users\brian\Desktop\nvidia-snatcher\build\notification\notification.js
- C:\Users\brian\Desktop\nvidia-snatcher\build\notification\index.js
- C:\Users\brian\Desktop\nvidia-snatcher\build\store\lookup.js
- C:\Users\brian\Desktop\nvidia-snatcher\build\store\index.js
- C:\Users\brian\Desktop\nvidia-snatcher\build\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\brian\Desktop\nvidia-snatcher\build\notification\pushbullet.js:8:38)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\brian\\Desktop\\nvidia-snatcher\\build\\notification\\pushbullet.js',
    'C:\\Users\\brian\\Desktop\\nvidia-snatcher\\build\\notification\\notification.js',
    'C:\\Users\\brian\\Desktop\\nvidia-snatcher\\build\\notification\\index.js',
    'C:\\Users\\brian\\Desktop\\nvidia-snatcher\\build\\store\\lookup.js',
    'C:\\Users\\brian\\Desktop\\nvidia-snatcher\\build\\store\\index.js',
    'C:\\Users\\brian\\Desktop\\nvidia-snatcher\\build\\index.js'
  ]
}

**Comment by emike09** [comment]
Same here. Just did my daily update via git.

**Comment by emike09** [comment]
Do another git pull origin main. It should work, 2 files were modified since my last pull.

**Comment by jef** [comment]
Don't forget `npm install`!
